# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://gyanig.github.io"
baseurl: ""

# Name of website
title: Gyanig K.

# Short description of your site
description: Personal Website

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Home: ""
  Publications: "publications"
  Blog: "blog"
  Resume: "resume"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Gyanig Kumar
  email: "gyanig.kumar@gmail.com"
  github: gyanigk
  linkedin: "gyanig-k-b36666146"
  twitter: "p4rZ_"

# Select which links to show in the footer
footer-links-active:
  rss: false
  email: true
  twitter: true
  github: true
  linkedin: true

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: false
  google: true
  linkedin: false

# How to display the link to the website in the footer
url-pretty: "gyanig.github.io"

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "gyanig-github-io"

# Fill in your Google Analytics ID to track your website using GA
# google_analytics: "G-7S1G3392FP"

# Excerpt Word Length
excerpt_length: 50

# Character used to separate site title and description in HTML document title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options
timezone: "America/Denver"
markdown: kramdown
mathjax: true
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true

# Use tags pages
link-tags: false

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - Vagrantfile

gems:
  - jekyll-paginate 